import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DomainError, WorkbenchStore, WorkflowService, STAGED_PLANNING_ADAPTER, STAGED_EXECUTION_ADAPTER, digest, executionInputDigest, executionInputs, executionArtifactRefs } from '../src/domain/index.ts';
import type { ArtifactRef, Demand, ExecutionFindingInput, ExecutionWorkStep, ReportVerification, RunAttempt, UserCommand, WorkerReport } from '../src/domain/types.ts';

// Synthetic trusted observations test the persisted rule engine. They do not
// establish actual OS isolation, actual TDD quality, or real model execution.
const ref = (id: string): ArtifactRef => ({ id, digest: `sha256-${id}`, location: `fixture://${id}` });
const stopProof = { processAbsent: true, descendantsAbsent: true, workspaceVerified: true, evidence: 'Synthetic process-tree absence and owned worktree observation.' };
const dispatch = { profileVerified: true, budgetAvailable: true, workspaceVerified: true, demandId: 'd' };
const error = (code: string) => (value: unknown) => value instanceof DomainError && value.code === code;
const methods = { planning: { id: 'design', version: '1', digest: 'design-method', adapter: STAGED_PLANNING_ADAPTER }, implementation: { id: 'implement', version: '1', digest: 'implement-method', adapter: STAGED_EXECUTION_ADAPTER }, review: { id: 'implement', version: '1', digest: 'implement-method', adapter: STAGED_EXECUTION_ADAPTER } };
function fixture(options: { path?: string; tickets?: number; checks?: boolean; reviewAdapter?: string } = {}) {
  let store = new WorkbenchStore(options.path ?? ':memory:'), service = new WorkflowService(store), user = service.trustedUser('owner'), sequence = 0;
  service.createProject({ id: 'p', name: 'Synthetic', rootPath: '/synthetic', methods: { ...methods, review: { ...methods.review, adapter: options.reviewAdapter ?? STAGED_EXECUTION_ADAPTER } }, baseChecks: options.checks === false ? [] : [{ id: 'required', name: 'Actual required check', source: 'project' }] });
  service.createDemand({ id: 'd', projectId: 'p', title: 'Persist approved ticket execution' });
  service.execute({ requestId: 'start', demandId: 'd', type: 'start-planning' }, user);
  const approved = service.getDemand('d'), understanding = { id: 'U', scope: 'Preserve durable ordering.', acceptanceCriteria: ['Restart preserves ordering.'], nonGoals: ['Remote publication'], constraints: ['Single writer.'], evidence: ref('understanding'), version: 1, digest: 'approved-understanding', createdByRun: 'planning-understanding', contextId: 'understanding-context' }, design = { id: 'D', understandingDigest: understanding.digest, summary: 'Host persists ticket and review transitions.', testingSeams: ['Interrupt after durable receipt.'], constraints: ['Use the existing local API.'], evidence: ref('design'), version: 1, digest: 'approved-design', createdByRun: 'planning-design', contextId: 'design-context' };
  const tickets = Array.from({ length: options.tickets ?? 2 }, (_, i) => ({ id: `T${i + 1}`, kind: 'ticket' as const, title: `Persist behavior ${i + 1}`, evidence: ref(`T${i + 1}`), specId: 'S', specClauses: [`AC-${i + 1}`], blockedBy: i ? [`T${i}`] : [] }));
  approved.planningFlow = { id: 'planning-flow', revision: 12, step: 'complete', history: [], messages: [], questions: [], answers: [], confirmations: [], understanding, design, understandingConfirmation: { kind: 'understanding', targetId: 'U', digest: understanding.digest, flowRevision: 3, userId: 'owner', createdAt: '2026-10-09T00:00:00Z' }, finalDesignConfirmation: { kind: 'final-design', targetId: 'D', digest: 'approved-final', flowRevision: 9, userId: 'owner', createdAt: '2026-10-09T00:00:00Z' }, review: { id: 'DR', designDigest: design.digest, evidence: ref('design-review'), findings: [], runId: 'design-review-run', contextId: 'design-review-context', inputDigest: 'design-review-input' }, resolution: { id: 'DZ', reviewId: 'DR', designDigest: design.digest, evidence: ref('design-resolution'), dispositions: [], digest: 'approved-final', createdByRun: 'design-resolution-run' }, spec: { id: 'S', kind: 'spec', designDigest: design.digest, evidence: ref('spec'), requiredChecks: [], createdByRun: 'spec-run' }, tickets };
  approved.plans = [{ id: 'P', scope: understanding.scope, spec: ref('spec'), tickets: ref('ticket-index'), requiredChecks: [], unresolvedQuestions: [], ready: true, createdByRun: 'tickets-run', designBinding: { flowId: 'planning-flow', understandingDigest: understanding.digest, designDigest: design.digest, finalConfirmationDigest: 'approved-final' } }];
  approved.activePlanId = 'P'; approved.confirmedPlanId = 'P'; approved.phase = 'awaiting-authorization'; store.saveDemand(approved);
  const demand = () => service.getDemand('d'), flow = () => demand().executionFlow!;
  const command = (body: any) => service.execute({ requestId: `u${++sequence}`, demandId: 'd', expectedRevision: demand().revision, ...body } as UserCommand, user);
  const authorize = () => command({ type: 'authorize-implementation', planId: 'P' });
  const claim = (step: ExecutionWorkStep) => { const run = service.claimNextRun(dispatch); assert.ok(run, `Expected ${step}`); assert.equal(run.executionStep, step); return run; };
  const binding = (run: RunAttempt) => ({ flowId: flow().id, flowRevision: flow().revision, inputDigest: executionInputDigest(demand(), run.executionStep!), executionStep: run.executionStep!, scope: flow().scope, ticketId: flow().ticketId, contentId: demand().activeContentId });
  const verification = (run: RunAttempt, body: any): ReportVerification => ({ artifactsVerified: true, contentStable: true, reviewInputsVerified: true, executionStage: { runId: run.id, executionStep: run.executionStep!, flowId: flow().id, flowRevision: flow().revision, inputDigest: executionInputDigest(demand(), run.executionStep!), baseCommit: 'verified-base-commit', sourceVerified: true, requiredSkillVerified: true, actualRunObserved: true, actualStopVerified: true, tddVerified: true }, ...(run.stage === 'review' ? { executionIndependent: { axis: run.executionStep!.endsWith('standards') ? 'standards' as const : 'spec' as const, runId: run.id, contextId: run.contextId, flowId: flow().id, flowRevision: flow().revision, contentId: demand().activeContentId!, inputDigest: executionInputDigest(demand(), run.executionStep!), evidenceDigest: (body.review?.evidence ?? body.resolution?.evidence ?? ref('check')).digest, actualRunObserved: true, isolatedInputsVerified: true, readOnlyVerified: true } } : {}) });
  const report = (run: RunAttempt, body: any, observed?: ReportVerification) => service.report({ requestId: `w${++sequence}`, demandId: 'd', runId: run.id, generation: run.generation, ...binding(run), ...body } as WorkerReport, service.workerContext(run.id), observed ?? verification(run, body));
  const stop = (run: RunAttempt) => service.confirmStopped(run.id, stopProof);
  const content = (name = `K${sequence}`, mode: 'red-green' | 'preserve-behavior' = 'red-green') => ({ type: 'execution-content', content: { id: name, planId: 'P', code: ref(`code-${name}`), knowledge: [ref(`notes-${name}`)], maintenance: 'complete', deliveryNotes: 'Private writer summary must stay outside independent review input.' }, tdd: { mode, ...(mode === 'preserve-behavior' ? { rationale: 'Documented naming-only repair preserves behavior.' } : {}), testingSeams: ['Interrupt after durable receipt.'], red: mode === 'red-green' ? [ref(`red-${name}`)] : [], green: [ref(`green-${name}`)] }, ...(flow().step === 'ticket-fix' ? { repairScopeId: flow().repairScope!.id } : {}) });
  const write = (name?: string, mode?: 'red-green' | 'preserve-behavior') => { const run = claim(flow().step as ExecutionWorkStep); report(run, content(name, mode)); stop(run); return run; };
  const reviewBody = (axis: 'standards' | 'spec', findings: ExecutionFindingInput[] = []) => ({ type: 'execution-review', review: { id: `R${sequence}`, axis, contentId: demand().activeContentId!, evidence: ref(`review-${sequence}`), knowledgeReviewed: true, findings } });
  const check = (run: RunAttempt, status: 'passed' | 'failed' | 'unavailable' = 'passed') => report(run, { type: 'check', check: { id: `C${sequence}`, contentId: demand().activeContentId!, requirementId: 'required', status, evidence: ref(`check-${sequence}`), environment: 'Actual receipt fixture.' } });
  const review = (axis: 'standards' | 'spec', findings: ExecutionFindingInput[] = []) => { const run = claim(`review-${axis}`); if (options.checks !== false) check(run); report(run, reviewBody(axis, findings)); stop(run); return run; };
  const resolutionBody = (axis: 'standards' | 'spec', outcome = 'fixed') => { const scope = flow().repairScope!, selected = flow().reviews.filter(review => scope.reviewIds.includes(review.id) && review.axis === axis).flatMap(review => review.findings).filter(finding => scope.findingIds.includes(finding.id)); return { type: 'execution-resolution', resolution: { id: `Z${sequence}`, axis, contentId: demand().activeContentId!, repairScopeId: scope.id, evidence: ref(`resolution-${sequence}`), dispositions: selected.map(finding => ({ findingId: finding.id, outcome, rationale: 'Verified the focused scenario and actual evidence.', evidence: ref(`fixed-${finding.id}-${sequence}`) })) } }; };
  const resolve = (axis: 'standards' | 'spec', outcome?: string) => { const run = claim(`resolution-${axis}`); if (options.checks !== false) check(run); report(run, resolutionBody(axis, outcome)); stop(run); return run; };
  const implementAll = () => { authorize(); while (flow().step === 'ticket-implementation') write(); };
  const restart = () => { store.close(); store = new WorkbenchStore(options.path!); service = new WorkflowService(store); user = service.trustedUser('owner'); };
  return { get store() { return store; }, get service() { return service; }, demand, flow, command, authorize, claim, binding, verification, report, stop, content, write, reviewBody, check, review, resolutionBody, resolve, implementAll, restart };
}
const standard = (id = 'F-standard'): ExecutionFindingInput => ({ id, severity: 'blocking', category: 'documented-violation', location: 'src/store.ts:17', reference: ref('documented-standard'), basis: 'Project standard requires atomic commits.', impact: 'A partial update could persist.', verification: 'Interrupt after the receipt.', requiresDesignDecision: false });
const specFinding = (id = 'F-spec'): ExecutionFindingInput => ({ ...standard(id), category: 'spec-violation', reference: ref('spec'), clause: 'AC-1', basis: 'Approved AC-1 requires durable ordering.' });

test('serial ticket frontier requires TDD, verified writer stop, then exactly one whole-spec two-axis review', () => {
  const f = fixture(); f.authorize(); const first = f.claim('ticket-implementation'); assert.equal(first.executionTicketId, 'T1'); assert.equal(first.writer, true); assert.equal(f.service.claimNextRun(dispatch), null);
  f.report(first, f.content('K1')); assert.equal(f.flow().tickets[0]!.status, 'done'); assert.equal(f.flow().ticketId, 'T2'); assert.equal(f.flow().reviews.length, 0); assert.equal(f.service.claimNextRun(dispatch), null); f.stop(first);
  const second = f.write('K2'); assert.equal(second.executionTicketId, 'T2'); assert.equal(f.flow().scope, 'whole-spec'); assert.equal(f.flow().step, 'review-standards'); assert.ok(f.flow().tickets.every(ticket => ticket.status === 'done'));
  const standards = f.review('standards'); assert.equal(f.demand().activeResultId, undefined); const spec = f.claim('review-spec'); assert.notEqual(spec.contextId, standards.contextId); assert.equal(spec.contentId, standards.contentId); f.check(spec); f.report(spec, f.reviewBody('spec'));
  assert.equal(f.flow().step, 'complete'); assert.equal(f.demand().activeResultId, undefined); assert.equal(f.service.claimNextRun(dispatch), null); f.stop(spec);
  assert.equal(f.demand().phase, 'awaiting-acceptance'); assert.equal(f.flow().reviews.length, 2); assert.equal(f.flow().implementations.length, 2); assert.equal(f.demand().results[0]!.contentId, 'K2'); assert.equal(f.demand().results[0]!.execution!.reviews.length, 2); assert.equal(f.demand().results[0]!.execution!.step, 'complete'); assert.equal(f.flow().baseCommit, 'verified-base-commit'); f.store.close();
});

test('paired adapter and approved spec/design/seams fail closed; legacy fixtures remain covered separately', () => {
  const mismatch = fixture({ reviewAdapter: 'legacy' }); assert.throws(() => mismatch.authorize(), error('EXECUTION_METHOD_PAIR_REQUIRED')); assert.equal(mismatch.demand().grant, undefined); mismatch.store.close();
  for (const missing of ['spec', 'design', 'finalDesignConfirmation'] as const) { const f = fixture(); const d = f.demand(); delete d.planningFlow![missing]; f.store.saveDemand(d); assert.throws(() => f.authorize(), (value: unknown) => value instanceof DomainError); assert.equal(f.demand().executionFlow, undefined); f.store.close(); }
  const f = fixture(); f.authorize(); const run = f.claim('ticket-implementation');
  for (const type of ['content-ready', 'review', 'resolve-finding', 'dispute']) assert.throws(() => f.report(run, { type, content: f.content().content }), error('STAGED_EXECUTION_REPORT_REQUIRED'));
  f.store.close();
});

test('content cannot advance without exact TDD, approved seams, immutable base and Host verified observations', () => {
  const f = fixture(); f.authorize(); const run = f.claim('ticket-implementation'), body = f.content('K1');
  for (const key of ['sourceVerified', 'requiredSkillVerified', 'actualRunObserved', 'actualStopVerified', 'tddVerified'] as const) { const observed = f.verification(run, body); observed.executionStage![key] = false; assert.throws(() => f.report(run, body, observed), error(key === 'tddVerified' ? 'EXECUTION_TDD_UNVERIFIED' : 'EXECUTION_STAGE_UNVERIFIED')); }
  const noBase = f.verification(run, body); noBase.executionStage!.baseCommit = ''; assert.throws(() => f.report(run, body, noBase), error('INVALID_EXECUTION'));
  assert.throws(() => f.report(run, { ...body, tdd: { ...body.tdd, red: [] } }), error('EXECUTION_TDD_REQUIRED'));
  assert.throws(() => f.report(run, { ...body, tdd: { ...body.tdd, testingSeams: ['New invasive seam.'] } }), error('EXECUTION_TDD_SEAMS_UNBOUND'));
  assert.throws(() => f.report(run, f.content('K1', 'preserve-behavior')), error('EXECUTION_TDD_BEHAVIOR_REQUIRED'));
  assert.throws(() => f.report(run, { ...body, inputDigest: 'forged-input' }), error('STALE_EXECUTION'));
  f.report(run, body); f.stop(run); const next = f.claim('ticket-implementation'), observed = f.verification(next, f.content('K2')); observed.executionStage!.baseCommit = 'changed-base'; assert.throws(() => f.report(next, f.content('K2'), observed), error('EXECUTION_BASE_CHANGED')); f.store.close();
});

test('broad review inputs exclude writer narrative and other-axis findings, while focused inputs include only their axis', () => {
  const f = fixture(); f.implementAll(); const before = executionInputs(f.demand(), 'review-standards'); assert.ok(!JSON.stringify(before).includes('Private writer summary')); assert.ok(!('targetedReviews' in before));
  f.review('standards', [standard()]); const spec = executionInputs(f.demand(), 'review-spec'); assert.equal(spec.content!.id, before.content!.id); assert.ok(!JSON.stringify(spec).includes('F-standard')); assert.ok(!executionArtifactRefs(f.demand(), 'review-spec').some(item => item.id.startsWith('review-')));
  f.review('spec', [specFinding()]); f.write('K-repaired'); const focused = executionInputs(f.demand(), 'resolution-standards'); assert.equal(focused.targetedReviews!.length, 1); assert.equal(focused.targetedReviews![0]!.axis, 'standards'); assert.ok(!JSON.stringify(focused).includes('F-spec')); assert.ok(!JSON.stringify(focused).includes('Private writer summary')); assert.equal(focused.repairEvidence!.contentId, 'K-repaired'); assert.equal(focused.repairEvidence!.green[0]!.id, 'green-K-repaired'); assert.ok(!executionArtifactRefs(f.demand(), 'resolution-standards').some(item => item.id.startsWith('review-'))); f.store.close();
});

test('one writer repairs exact finding scope; independent focused resolutions close both axes without broad review recursion', () => {
  const f = fixture(); f.implementAll(); f.review('standards', [standard(), { ...standard('smell'), category: 'smell', severity: 'suggestion' }]); f.review('spec', [specFinding()]);
  assert.equal(f.flow().step, 'ticket-fix'); assert.deepEqual(f.flow().repairScope!.findingIds, ['F-standard', 'F-spec']); assert.equal(f.flow().repairScope!.reviewIds.length, 2); const scopeId = f.flow().repairScope!.id;
  const writer = f.claim('ticket-fix'); assert.throws(() => f.report(writer, { ...f.content('K-repaired'), repairScopeId: 'other' }), error('EXECUTION_REPAIR_REQUIRED')); assert.throws(() => f.report(writer, f.content('K-repaired', 'preserve-behavior')), error('EXECUTION_TDD_BEHAVIOR_REQUIRED')); f.report(writer, f.content('K-repaired')); f.stop(writer);
  const standards = f.claim('resolution-standards'), wrong = f.resolutionBody('standards'); wrong.resolution.dispositions.push({ findingId: 'F-spec', outcome: 'fixed', rationale: 'Wrong axis.', evidence: ref('wrong') }); assert.throws(() => f.report(standards, wrong), error('EXECUTION_RESOLUTION_SCOPE')); f.check(standards); f.report(standards, f.resolutionBody('standards')); f.stop(standards);
  f.resolve('spec'); assert.equal(f.flow().step, 'complete'); assert.equal(f.flow().reviews.length, 2); assert.equal(f.flow().resolutions.length, 2); assert.equal(f.flow().repairHistory[0]!.id, scopeId); assert.equal(f.demand().findings.find(item => item.id === 'smell')!.status, 'open'); assert.equal(f.demand().results[0]!.contentId, 'K-repaired'); assert.equal(f.demand().results[0]!.findingClosures.length, 2); assert.equal(f.demand().results[0]!.execution!.resolutions.length, 2); f.store.close();
});

test('standards-only behavior-preserving repair uses actual green evidence without manufacturing a red failure', () => {
  const f = fixture(); f.implementAll(); f.review('standards', [standard()]); f.review('spec'); f.write('K-style', 'preserve-behavior'); assert.equal(f.flow().implementations.at(-1)!.tdd.mode, 'preserve-behavior'); f.resolve('standards'); assert.equal(f.flow().resolutions.length, 1); assert.equal(f.demand().phase, 'awaiting-acceptance'); f.store.close();
});

test('missing actual check evidence leaves whole-spec review pending; failed checks become explicit repair obligations', () => {
  const f = fixture(); f.implementAll(); const standards = f.claim('review-standards'); f.report(standards, f.reviewBody('standards')); f.stop(standards); const spec = f.claim('review-spec'); assert.throws(() => f.report(spec, f.reviewBody('spec')), error('EXECUTION_CHECKS_MISSING')); assert.equal(f.flow().reviews.length, 1); assert.equal(f.flow().step, 'review-spec');
  const input = executionInputDigest(f.demand(), 'review-spec'); f.check(spec, 'failed'); assert.equal(executionInputDigest(f.demand(), 'review-spec'), input); f.report(spec, f.reviewBody('spec')); f.stop(spec); assert.deepEqual(f.flow().repairScope!.checkIds, ['required']); assert.deepEqual(f.flow().repairScope!.findingIds, []);
  const writer = f.claim('ticket-fix'); assert.throws(() => f.report(writer, f.content('K-tests', 'preserve-behavior')), error('EXECUTION_TDD_BEHAVIOR_REQUIRED')); f.report(writer, f.content('K-tests')); f.stop(writer); assert.equal(f.flow().step, 'resolution-spec'); f.resolve('spec'); assert.equal(f.demand().phase, 'awaiting-acceptance'); f.store.close();
});

test('finding taxonomy, exact spec references and actual reviewer isolation cannot be self asserted', () => {
  const f = fixture(); f.implementAll(); const run = f.claim('review-standards'), body = f.reviewBody('standards');
  const observed = f.verification(run, body); observed.executionIndependent!.contextId = 'writer-context'; assert.throws(() => f.report(run, body, observed), error('EXECUTION_INDEPENDENCE_UNVERIFIED'));
  assert.throws(() => f.report(run, f.reviewBody('standards', [{ ...standard(), category: 'smell' }])), error('EXECUTION_SMELL_NOT_VIOLATION'));
  assert.throws(() => f.report(run, f.reviewBody('standards', [specFinding()])), error('EXECUTION_FINDING_AXIS'));
  assert.throws(() => f.report(run, f.reviewBody('standards', [{ ...standard(), requiresDesignDecision: true }])), error('USER_DECISION_REQUIRED'));
  f.report(run, body); f.stop(run); const spec = f.claim('review-spec'); assert.throws(() => f.report(spec, f.reviewBody('spec', [{ ...specFinding(), reference: ref('different-spec') }])), error('EXECUTION_SPEC_FINDING_UNBOUND')); f.store.close();
});

test('pause, restart, recovered runs and stale revisions cannot advance the saved flow or reopen the writer', () => {
  const directory = mkdtempSync(join(tmpdir(), 'execution-domain-')), f = fixture({ path: join(directory, 'state.db') });
  try { f.authorize(); const run = f.claim('ticket-implementation'), body = f.content('K-late'), binding = f.binding(run), verification = f.verification(run, body); f.command({ type: 'pause' }); const late = f.service.report({ requestId: 'late-paused', demandId: 'd', runId: run.id, generation: run.generation, ...binding, ...body } as WorkerReport, f.service.workerContext(run.id), verification); assert.equal(late.status, 'historical'); assert.equal(f.demand().activeContentId, undefined); f.stop(run); f.restart(); assert.equal(f.demand().control, 'paused'); assert.equal(f.flow().step, 'ticket-implementation'); assert.equal(f.service.claimNextRun(dispatch), null);
    f.command({ type: 'resume' }); const resumed = f.claim('ticket-implementation'); assert.notEqual(resumed.contextId, run.contextId); f.service.markInterrupted(resumed.id, 'Synthetic restart loss.'); f.service.recoverRun(resumed.id, { ...stopProof, profileVerified: true, budgetAvailable: true }); assert.equal(f.report(resumed, f.content('obsolete')).status, 'historical'); const next = f.claim('ticket-implementation'); f.report(next, f.content('K1')); f.stop(next); f.write('K2'); f.review('standards'); const record = f.flow().reviews[0]; f.restart(); assert.deepEqual(f.flow().reviews[0], record); f.review('spec'); assert.equal(f.demand().phase, 'awaiting-acceptance');
  } finally { f.store.close(); rmSync(directory, { recursive: true, force: true }); }
});

test('returned result preserves immutable history, reopens the whole ticket graph and cannot reuse old review acceptance', () => {
  const f = fixture(); f.implementAll(); f.review('standards'); f.review('spec'); const first = structuredClone(f.demand().results[0]!); f.command({ type: 'accept-result', resultId: first.id }); f.command({ type: 'return-result', resultId: first.id, reason: 'Exercise interrupted startup on every ticket.' }); assert.equal(f.flow().scope, 'ticket'); assert.equal(f.flow().step, 'ticket-implementation'); assert.ok(f.flow().tickets.every(ticket => ticket.status === 'pending')); assert.equal(f.flow().history.length, 1); assert.equal(f.flow().history[0]!.reviews.length, 2); assert.equal(f.flow().reviews.length, 0); assert.deepEqual(f.demand().results[0], first);
  const returned = executionInputs(f.demand(), 'ticket-implementation'); assert.equal(returned.returnInstruction!.reason, 'Exercise interrupted startup on every ticket.'); assert.equal(returned.returnInstruction!.resultId, first.id); assert.deepEqual(returned.returnInstruction!.code, first.K); const priorDigest = executionInputDigest(f.demand(), 'ticket-implementation'), changed = f.demand(); changed.executionFlow!.returnInstruction!.reason = 'Changed rejection context.'; assert.notEqual(executionInputDigest(changed, 'ticket-implementation'), priorDigest);
  f.write('K3'); f.write('K4'); assert.ok(!('returnInstruction' in executionInputs(f.demand(), 'review-standards'))); f.review('standards'); assert.equal(f.demand().activeResultId, undefined); f.review('spec'); assert.notEqual(f.demand().activeResultId, first.id); assert.throws(() => f.command({ type: 'accept-result', resultId: first.id }), error('STALE_RESULT')); f.store.close();
});

test('stage report replay is durable and changed request payload cannot duplicate ticket advancement', () => {
  const f = fixture(); f.authorize(); const run = f.claim('ticket-implementation'), body = f.content('K1'), verification = f.verification(run, body), report = { requestId: 'once', demandId: 'd', runId: run.id, generation: run.generation, ...f.binding(run), ...body } as WorkerReport, worker = f.service.workerContext(run.id); const receipt = f.service.report(report, worker, verification); assert.deepEqual(f.service.report(report, worker, verification), receipt); assert.equal(f.flow().implementations.length, 1); assert.throws(() => f.service.report({ ...report, content: f.content('K-changed').content } as WorkerReport, worker, verification), error('IDEMPOTENCY_CONFLICT')); f.store.close();
});


test('eligible frontier handles unsorted acyclic tickets and rejects cycles or missing dependencies', () => {
  const f = fixture({ tickets: 3 }); const d = f.demand(); d.planningFlow!.tickets.reverse(); f.store.saveDemand(d); f.authorize(); assert.equal(f.flow().ticketId, 'T1'); f.write('K1'); assert.equal(f.flow().ticketId, 'T2'); f.write('K2'); assert.equal(f.flow().ticketId, 'T3'); f.write('K3'); assert.equal(f.flow().scope, 'whole-spec'); f.store.close();
  for (const dependency of ['T2', 'missing']) { const invalid = fixture(); const bad = invalid.demand(); bad.planningFlow!.tickets[0]!.blockedBy = [dependency]; invalid.store.saveDemand(bad); assert.throws(() => invalid.authorize(), error('INVALID_TICKETS')); assert.equal(invalid.demand().grant, undefined); invalid.store.close(); }
});

test('open behavior decisions survive generic blocker clearing and approved seams cannot silently change', () => {
  const f = fixture(); f.implementAll(); f.review('standards', [{ ...standard('decision'), severity: 'decision', requiresDesignDecision: true }]); assert.equal(f.demand().phase, 'blocked'); assert.equal(f.service.claimNextRun(dispatch), null); f.command({ type: 'resolve-blocker', reason: 'Retry transport.' }); assert.equal(f.service.claimNextRun(dispatch), null); assert.equal(f.demand().findings.find(item => item.id === 'decision')!.status, 'open');
  f.command({ type: 'decide-finding', findingId: 'decision', reason: 'Keep the approved behavior and testing seams; no scope change.' }); assert.equal(f.flow().step, 'review-spec'); const changed = f.demand(); changed.planningFlow!.design!.testingSeams.push('Unapproved seam.'); assert.throws(() => executionInputs(changed, 'review-spec'), error('EXECUTION_APPROVAL_CHANGED')); f.review('spec'); assert.equal(f.demand().phase, 'awaiting-acceptance'); f.store.close();
});

test('unresolved focused findings create another bounded repair without restarting broad reviews', () => {
  const f = fixture(); f.implementAll(); f.review('standards', [standard()]); f.review('spec'); const oldScope = f.flow().repairScope!.id; f.write('K-repair1'); f.resolve('standards', 'unresolved'); assert.equal(f.flow().step, 'ticket-fix'); assert.notEqual(f.flow().repairScope!.id, oldScope); assert.equal(f.flow().reviews.length, 2); assert.deepEqual(f.flow().repairScope!.findingIds, ['F-standard']); const repair = executionInputs(f.demand(), 'ticket-fix'); assert.equal(repair.priorDispositions!.at(-1)!.outcome, 'unresolved'); f.write('K-repair2'); f.resolve('standards'); assert.equal(f.flow().reviews.length, 2); assert.equal(f.flow().resolutions.length, 2); assert.equal(f.demand().phase, 'awaiting-acceptance'); f.store.close();
});

test('explicit blocker clarification reaches only the resumed eligible writer and binds its unchanged approved scope', () => {
  const f = fixture(); f.authorize(); const first = f.claim('ticket-implementation'), before = f.binding(first).inputDigest; f.report(first, { type: 'blocked', reason: 'Which local fixture should exercise the approved interruption seam?' }); f.stop(first); f.command({ type: 'resolve-blocker', reason: 'Use the existing local durable-receipt fixture; keep the approved seam.' }); const resumed = f.claim('ticket-implementation'), inputs = executionInputs(f.demand(), 'ticket-implementation'); assert.notEqual(f.binding(resumed).inputDigest, before); assert.equal(inputs.userDecisions!.length, 1); assert.equal(inputs.userDecisions![0]!.reason, 'Use the existing local durable-receipt fixture; keep the approved seam.'); assert.equal(inputs.userDecisions![0]!.permitsScopeChange, false); assert.equal(inputs.userDecisions![0]!.approvedInputDigest, f.flow().approvedInputDigest); f.report(resumed, f.content('K1')); f.stop(resumed);
  assert.deepEqual(executionInputs(f.demand(), 'ticket-implementation').userDecisions, []); f.write('K2'); const review = executionInputs(f.demand(), 'review-standards'); assert.ok(!('userDecisions' in review)); assert.ok(!JSON.stringify(review).includes('durable-receipt fixture')); f.store.close();
});
