import { Type } from '@earendil-works/pi-ai';
import type { TSchema } from '@earendil-works/pi-ai';
import type { RuntimeRole } from '../runtime/types.ts';

const strict = { additionalProperties: false };
const id = () => Type.String({ minLength: 1, maxLength: 200, pattern: '^[A-Za-z0-9][A-Za-z0-9_.:/@-]*$' });
const text = (description: string) => Type.String({ minLength: 1, maxLength: 65536, description });
const ref = () => Type.Object({ id: id(), digest: Type.String({ minLength: 1, description: 'Exact returned digest; use pending only for a matching new artifact body or current-worktree code snapshot.' }), location: Type.String({ minLength: 1, description: 'Exact returned pi-object reference; host-artifact for a matching artifactBodies entry; current-worktree only for implementation code.' }) }, strict);
const artifactBodies = Type.Optional(Type.Array(Type.Object({ id: id(), kind: Type.Union([Type.Literal('plan'), Type.Literal('knowledge'), Type.Literal('check-evidence')]), text: text('The complete immutable UTF-8 artifact body, not a path or a summary of an unavailable artifact.') }, strict), { maxItems: 32 }));
const blocked = Type.Object({ type: Type.Literal('blocked'), reason: text('Concrete missing input, unresolved decision, failed capability, or permission required.') }, strict);
const messages = [Type.Object({ type: Type.Literal('message-delivered'), messageId: id() }, strict), Type.Object({ type: Type.Literal('message-applied'), messageId: id() }, strict)];
const planDraft = Type.Object({ type: Type.Literal('plan-draft'), plan: Type.Object({ id: id(), scope: text('Only the user-requested scope; tickets are internal execution tasks.'), spec: ref(), tickets: ref(), requiredChecks: Type.Array(Type.Object({ id: id(), name: text('Concrete required verification of requested behavior.'), source: Type.Union([Type.Literal('project'), Type.Literal('demand')]), highResource: Type.Optional(Type.Boolean()) }, strict), { maxItems: 128 }), unresolvedQuestions: Type.Array(text('An unresolved user decision; do not invent its answer.'), { maxItems: 128 }) }, strict), artifactBodies }, strict);
const planReady = Type.Object({ type: Type.Literal('plan-ready'), planId: id(), boundaryReview: Type.Object({ contextId: id(), planningContextId: id(), evidence: ref(), unresolvedBlockingFindings: Type.Array(text('Unresolved boundary blocker.'), { maxItems: 128 }) }, strict), artifactBodies }, strict);
const contentReady = Type.Object({ type: Type.Literal('content-ready'), content: Type.Object({ id: id(), planId: id(), code: ref(), knowledge: Type.Array(ref(), { maxItems: 128 }), maintenance: Type.Union([Type.Literal('complete'), Type.Literal('not-needed')]), deliveryNotes: text('What changed, scope/verification notes, and explicit local-maintenance conclusion; do not claim independent acceptance.') }, strict), artifactBodies }, strict);
const finding = Type.Object({ id: id(), severity: Type.Union([Type.Literal('blocking'), Type.Literal('suggestion'), Type.Literal('decision')]), location: text('Exact source/material location.'), basis: text('Applicable requirement or evidence.'), impact: text('Concrete consequence.'), verification: text('How a fresh independent review can determine whether this is resolved.') }, strict);
const check = Type.Object({ type: Type.Literal('check'), check: Type.Object({ id: id(), contentId: id(), requirementId: id(), status: Type.Union([Type.Literal('passed'), Type.Literal('failed'), Type.Literal('unavailable')]), evidence: ref(), environment: Type.String({ minLength: 1, description: 'Use host-observed. Host replaces this with its exact native environment; Worker labels are never proof.' }) }, strict) }, strict);
const review = Type.Object({ type: Type.Literal('review'), reviewId: id(), contentId: id(), evidence: ref(), knowledgeReviewed: Type.Boolean(), findings: Type.Array(finding, { maxItems: 128 }), artifactBodies }, strict);
const dispute = Type.Object({ type: Type.Literal('dispute'), findingId: id(), evidence: ref(), artifactBodies }, strict);
const resolveFinding = Type.Object({ type: Type.Literal('resolve-finding'), findingId: id(), contentId: id(), evidence: ref(), outcome: Type.Union([Type.Literal('fixed'), Type.Literal('false-positive'), Type.Literal('not-applicable')]), artifactBodies }, strict);

/** A model-facing adapter contract, not permission or evidence. The transport and
 * Host still bind identity, enforce role/current versions and independently verify facts. */
export function controlledReportParameters(role: RuntimeRole) {
  const reports: Record<RuntimeRole, TSchema[]> = { planning: [planDraft, blocked, ...messages], 'boundary-review': [planReady, blocked], implementation: [contentReady, dispute, blocked, ...messages], review: [check, review, resolveFinding, blocked, ...messages], check: [blocked] };
  return Type.Object({ report: Type.Union(reports[role]) }, strict);
}
const shared = `Host report adapter v1. Call controlled_report with {report:<one schema variant>}. The Worker binds requestId, runId, demandId and generation; omit them. User authorization, acceptance, runtime stop and baseline eligibility are never report variants. Reports do not prove their own truth.
Use bounded unique artifact and report IDs. An existing artifact reference must exactly preserve {id,digest,location} from approved material or tool output. To create a prose artifact include artifactBodies:[{id,kind,text}] in the same report and reference it as {id,digest:"pending",location:"host-artifact"}; kinds are plan, knowledge or check-evidence. IDs are immutable: changed content needs a new ID. Never invent filesystem locations or evidence digests.
P is plan-scope:<planId>, with exact spec/ticket refs, scope and demand requirements. project-checks:<projectId> supplies mandatory project checks. C is content-scope:<contentId>, binding the exact P, code K, local knowledge N, maintenance and delivery notes. rework-scope and user-decisions carry concrete requested corrections and finding IDs. Use those IDs exactly; do not silently broaden scope. A pending-stop-verification receipt means stored for later verification, not passed or ready. Finish your response after a complete terminal report so the Host can stop and verify the native Job.`;
const stageInstructions: Record<RuntimeRole, string> = {
  planning: `Use the user-selected frozen planning method to produce plan-draft with plan:{id,scope,spec,tickets,requiredChecks,unresolvedQuestions}. Supply spec and tickets as separate plan artifactBodies. Preserve every project check; add concrete demand checks with stable requirement IDs. Explicitly list unresolved questions. Do not submit plan-ready: after your terminal handoff the Host launches a genuinely separate boundary reviewer. Missing actual planning method/dependencies or required user decisions must be reported blocked.`,
  'boundary-review': `Independently inspect exact P, spec, tickets, current source and all project/demand check coverage with the frozen review method. Use the Host-provided contextId and planningContextId from the task prompt. Only submit plan-ready:{planId,boundaryReview:{contextId,planningContextId,evidence,unresolvedBlockingFindings:[]}} after no blocking scope/coverage/questions remain; include concrete observations as a new check-evidence artifact. Otherwise report blocked. Your separate native session and exact stopped inputs are independently verified by Host.`,
  implementation: `Implement only the authorized P using controlled_write and controlled_delete. Native Node/Git Bash tools are for source-preserving checks and private scratch; command-generated source changes stop further transmission. Read correction/finding IDs and explicit user decisions before rework. Submit content-ready:{content:{id,planId,code:{id,digest:"pending",location:"current-worktree"},knowledge:[...exact refs],maintenance:"complete"|"not-needed",deliveryNotes},artifactBodies:[...]}. The Host captures K after verified stop (and an explicitly granted local commit). Put necessary local maintenance in knowledge artifacts; an empty N with a justified not-needed conclusion is allowed. An evidence-backed dispute identifies the exact findingId; you cannot close review findings or decide user-scope questions.`,
  review: `Independently review exact P/C, actual source, N and existing evidence without implementation conversation. Run every required project/demand check using controlled_node or configured controlled_shell. Their visible Host receipt supplies the exact evidence ref, requestId, exitCode and reason. Submit check:{id,contentId,requirementId,status,evidence,environment:"host-observed"}; passed requires a native exited/zero receipt, and IDs must match P/C and the required check. If no native receipt can be obtained, report blocked, never fabricate an unavailable check artifact.
Submit review:{reviewId,contentId,evidence,knowledgeReviewed:true,findings:[{id,severity,location,basis,impact,verification}]} with a concrete new check-evidence artifact. Cover source correctness, required behavior and necessary local maintenance; zero findings is not proof by itself. Findings are blocking, suggestion, or decision; only users resolve decision findings. Independently recheck each fix and submit resolve-finding:{findingId,contentId,evidence,outcome:"fixed"|"false-positive"|"not-applicable"}; the latter two require a recorded dispute. A passed check alone does not replace a review or close findings.`,
  check: 'This is a Host-only check lane. No Agent model session or report is authorized.',
};
export function reportAdapterInstructions(role: RuntimeRole): string { return `${shared}\n\n${stageInstructions[role]}`; }
