import { useState } from 'react';
import type { Demand, ViewState } from './types.ts';
import { implementationUnavailable, makeImplementationAuthorization } from './implementation-model.ts';
import type { ImplementationInput } from './implementation-model.ts';
export function ImplementationAuthorization({ target, state, offline, pending, error, close, onSubmit }: { target: Demand; state: ViewState; offline: boolean; pending: boolean; error: string | null; close: () => void; onSubmit: (input: ImplementationInput) => void }) {
  const [input, setInput] = useState<ImplementationInput>({ localCommit: false, authorName: '', authorEmail: '' });
  const unavailable = implementationUnavailable(target, state);
  let invalid = false; try { makeImplementationAuthorization(target, input, 'validation-only'); } catch { invalid = true; }
  const disabled = offline || pending || !!unavailable || invalid;
  return <form onSubmit={event => { event.preventDefault(); if (!disabled) onSubmit(input); }}><div className="dialog-object"><div className="metadata"><span>需求版本</span><code>{target.id} · v{target.version}</code></div><div className="metadata"><span>绑定已确认方案</span><code>{target.plan?.id}</code></div></div><p className="safe-text">{target.plan?.scope}</p><p className="dialog-note">仅授权按照上述已确认方案实施。模型费用、资料传输和本地资源访问需要各自有效的有限授权，Host 每次执行前继续核验。</p><label className="authorization-consent"><input type="checkbox" checked={input.localCommit} onChange={event => setInput({ localCommit: event.target.checked, authorName: '', authorEmail: '' })} /><span>另外允许本方案在此需求工作区创建精确文件范围的本地 Git 提交。不会 push、创建 PR 或合并远端。</span></label>{input.localCommit ? <><label className="form-field">本地提交作者姓名<input required maxLength={200} value={input.authorName} onChange={event => setInput(current => ({ ...current, authorName: event.target.value }))} /></label><label className="form-field">本地提交作者邮箱<input required type="email" maxLength={320} value={input.authorEmail} onChange={event => setInput(current => ({ ...current, authorEmail: event.target.value }))} /></label><p className="dialog-note">此身份只用于用户授权的本地提交；Host 在实际执行停止并核验精确文件后创建提交。</p></> : <p className="dialog-note">未授予本地提交权限时，成果可以保留工作区变更并接受 Review。复用资格核验需要已提交且与成果完全对应的源代码。</p>}{!state.runtime.executionEnabled && <p className="stale-warning">运行条件尚未通过。保存授权不会立即启动未核验的执行。</p>}{unavailable && <p className="stale-warning" role="alert">{unavailable}</p>}{error && <p className="stale-warning" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button" onClick={close}>返回</button><button type="submit" className="button primary" disabled={disabled}>{pending ? '正在保存…' : '确认此方案的实施授权'}</button></div></form>;
}
