import { useId, useState } from 'react';
import type { KnowledgeRole, SourceKind } from '../../knowledge/index.ts';
import type { Demand, ViewState } from './types.ts';
import { KNOWLEDGE_LABELS, knowledgeUnavailable, makeKnowledgeAction } from './knowledge-model.ts';
import type { KnowledgeInput, KnowledgeReview } from './knowledge-model.ts';

const Fact = ({ label, value }: { label: string; value: string }) => <div className="metadata"><span>{label}</span><code>{value}</code></div>;
const SOURCE_LABELS: Record<SourceKind, string> = { implementation: '本轮新增实现', 'existing-fact': '已有正式事实', environment: '独立环境经验' };
const ROLE_LABELS: Record<KnowledgeRole, string> = { planner: '规划', implementer: '实施', reviewer: '独立 Review' };
const OBSERVATION_LABELS = { unknown: '尚未核实', open: 'PR 尚未合入', 'closed-unmerged': '关闭但未合入', 'wrong-target': '目标分支不匹配', merged: '已观察到合入' };
export function KnowledgePanel({ state, demand, offline, pending, onReview }: { state: ViewState; demand: Demand; offline: boolean; pending: boolean; onReview: (review: KnowledgeReview) => void }) {
  const view = demand.knowledgeLifecycle;
  if (!view) return <p className="detail-muted">Host 尚未提供知识生命周期记录。</p>;
  const action = (review: KnowledgeReview, label = KNOWLEDGE_LABELS[review.action]) => {
    const unavailable = knowledgeUnavailable(review, state);
    return <><button className="button compact" disabled={offline || pending || !!unavailable} onClick={() => onReview(structuredClone(review))}>{label}</button>{unavailable && <p className="decision-unavailable">{unavailable}</p>}</>;
  };
  return <section className="decision-panel knowledge-lifecycle" aria-label="知识与基线生命周期"><h2>本地经验与复用</h2><p className="detail-muted">保存、来源核验、复用资格和当前基线适用性分别记录。只读取与操作此需求明确关联的对象。</p>
    {view.blockers.length > 0 && <ul className="blocker-list">{view.blockers.map((blocker, index) => <li key={index}>{blocker}</li>)}</ul>}
    <article className="decision-card"><h3>成果材料</h3>{view.resultMaterials.length ? view.resultMaterials.map(material => <section className="finding-card" key={`${material.resultId}:${material.artifactId}`}><strong>{material.title}</strong><Fact label="成果" value={material.resultId} /><Fact label="材料" value={material.artifactId} /><p>{material.accepted ? '此成果已有用户验收记录' : '尚无此成果的用户验收记录'}</p>{action({ action: 'save-candidate', demand, resultId: material.resultId, artifactId: material.artifactId })}</section>) : <p>暂无具有确切成果引用的本地材料。</p>}</article>
    {view.candidates.map(candidate => <article className="decision-card" key={candidate.revisionId}><h3>{candidate.title}</h3><span className="tiny-pill">{candidate.status === 'verified' ? '复用资格已登记' : candidate.status === 'ineligible' ? '资格已撤销' : '本轮候选'}</span><Fact label="知识版本" value={candidate.revisionId} /><Fact label="来源成果" value={candidate.resultId} /><Fact label="来源分类" value={SOURCE_LABELS[candidate.sourceKind]} /><Fact label="陈述类型" value={candidate.statementKind} /><Fact label="适用角色" value={candidate.roles.map(role => ROLE_LABELS[role]).join('、')} /><Fact label="模块范围" value={candidate.modulePaths.join('、') || '未限定模块'} /><details className="knowledge-body"><summary>审阅精确候选正文</summary><pre>{candidate.body || '正文不可用；请查看 Host 阻塞。'}</pre></details>{candidate.status !== 'ineligible' && <>{action({ action: 'qualify', demand, revisionId: candidate.revisionId })}{action({ action: 'invalidate', demand, revisionId: candidate.revisionId })}</>}<p>已登记资格仍须匹配后续需求的实际基线、环境、角色与许可；不会自动扩大资料发送范围。</p></article>)}
    <article className="decision-card"><h3>GitHub 合入观察</h3>{view.remote ? <><Fact label="精确仓库 / PR" value={`${view.remote.owner}/${view.remote.repository} #${view.remote.pullRequest}`} /><Fact label="正式目标" value={view.remote.target} />{action({ action: 'observe-remote', demand })}</> : <><p>先绑定精确仓库与 PR。仅只读核验，不会 push、创建 PR 或合并。</p>{action({ action: 'bind-remote', demand })}</>}{view.observations.map(observation => <section className="finding-card" key={observation.observationId}><strong>{OBSERVATION_LABELS[observation.state]}</strong><Fact label="观察 ID" value={observation.observationId} /><Fact label="来源" value={observation.provenance === 'github-live' ? 'GitHub 实时只读响应' : '受控测试响应，不可证明真实合入'} /><Fact label="核验时间" value={observation.observedAt} /><Fact label="正式提交" value={observation.formalCommit ?? '未核实'} />{observation.problem && <p className="decision-unavailable">{observation.problem}</p>}</section>)}<p>远端显示合入后，Host 仍须核对正式树与已审阅成果，及真实原生能力检查。</p></article>
    <article className="decision-card"><h3>工作区基线</h3>{view.baseline ? <><Fact label="正式目标" value={view.baseline.formalTarget} /><Fact label="初始基线" value={view.baseline.initial ?? '空基线'} /><Fact label="当前已核验基线" value={view.baseline.current ?? '空基线'} /><Fact label="工作区 HEAD" value={view.baseline.head ?? '未提交'} />{action({ action: 'propose-baseline', demand })}</> : <p>尚无已准备的需求工作区。</p>}{view.proposals.map(proposal => <section className="finding-card" key={proposal.proposalId}><Fact label="基线方案" value={proposal.proposalId} /><Fact label="精确源提交" value={proposal.sourceCommit} /><Fact label="方案绑定 HEAD" value={proposal.expectedHead} /><p>{proposal.result?.state === 'verified' ? '整合后能力已核验' : proposal.result?.state === 'conflict' ? '存在整合冲突，尚未放行' : proposal.result ? '已整合，能力尚待核验' : '待明确授权整合'}</p>{proposal.result?.conflicts.length ? <ul className="blocker-list">{proposal.result.conflicts.map(path => <li key={path}>{path}</li>)}</ul> : null}{(!proposal.result || proposal.result.state === 'conflict') && action({ action: 'apply-baseline', demand, proposalId: proposal.proposalId }, proposal.result?.state === 'conflict' ? '核对并继续此整合' : undefined)}{proposal.result?.state === 'integrated-awaiting-verification' && action({ action: 'verify-baseline', demand, proposalId: proposal.proposalId })}</section>)}</article>
  </section>;
}
export function KnowledgeForm({ review, state, pending, offline, error, close, onSubmit }: { review: KnowledgeReview; state: ViewState; pending: boolean; offline: boolean; error: string | null; close: () => void; onSubmit: (input: KnowledgeInput) => void }) {
  const view = review.demand.knowledgeLifecycle!;
  const candidate = 'revisionId' in review ? view.candidates.find(item => item.revisionId === review.revisionId) : review.action === 'save-candidate' ? view.candidates.find(item => item.resultId === review.resultId && item.artifactId === review.artifactId) : undefined;
  const proposal = 'proposalId' in review ? view.proposals.find(item => item.proposalId === review.proposalId) : undefined;
  const fieldId = useId();
  const [input, setInput] = useState<KnowledgeInput>({ title: review.action === 'save-candidate' ? view.resultMaterials.find(item => item.resultId === review.resultId && item.artifactId === review.artifactId)?.title : '', baseline: view.baseline?.current ?? '', roles: [], checkIds: [], reviewed: false, independentOfDemand: false, authorName: proposal?.author?.name ?? '', authorEmail: proposal?.author?.email ?? '' });
  const set = <K extends keyof KnowledgeInput>(key: K, value: KnowledgeInput[K]) => setInput(current => ({ ...current, [key]: value, ...(key !== 'reviewed' ? { reviewed: false } : {}) }));
  const field = (label: string, key: keyof KnowledgeInput, options: { required?: boolean; placeholder?: string; type?: string; rows?: number; maxLength?: number } = {}) => <label className="form-field">{label}{options.rows ? <textarea value={String(input[key] ?? '')} rows={options.rows} maxLength={options.maxLength ?? 8000} required={options.required} placeholder={options.placeholder} onChange={event => setInput(current => ({ ...current, [key]: event.target.value, reviewed: false }))} /> : <input value={String(input[key] ?? '')} maxLength={options.maxLength ?? 512} type={options.type ?? 'text'} readOnly={!!proposal?.author && (key === 'authorName' || key === 'authorEmail')} required={options.required} placeholder={options.placeholder} onChange={event => setInput(current => ({ ...current, [key]: event.target.value, reviewed: false }))} />}</label>;
  const unavailable = knowledgeUnavailable(review, state);
  let invalid = false; try { makeKnowledgeAction(review, input, 'validation-only'); } catch { invalid = true; }
  const disabled = pending || offline || !!unavailable || invalid;
  const selectedResult = review.action === 'qualify' ? candidate?.resultId : input.resultId;
  const checks = view.checks.filter(check => check.resultId === selectedResult);
  return <form className="knowledge-form" onSubmit={event => { event.preventDefault(); if (!disabled) onSubmit(input); }}>
    <div className="dialog-object"><Fact label="需求对象 / 版本" value={`${review.demand.id} · v${review.demand.version}`} />{'revisionId' in review && <Fact label="精确知识版本" value={review.revisionId} />}{review.action === 'save-candidate' && <><Fact label="成果对象" value={review.resultId} /><Fact label="材料对象" value={review.artifactId} /></>}{proposal && <><Fact label="方案对象" value={proposal.proposalId} /><Fact label="正式目标" value={proposal.formalTarget} /><Fact label="源提交" value={proposal.sourceCommit} /><Fact label="原 HEAD" value={proposal.expectedHead} /><Fact label="原基线" value={proposal.expectedBaseline ?? '空基线'} />{proposal.result?.head && <Fact label="整合后 HEAD" value={proposal.result.head} />}</>}</div>
    {review.action === 'save-candidate' && <>{field('候选标题', 'title', { required: true })}<div className="form-field"><label htmlFor={`${fieldId}-source-kind`}>来源分类</label><select id={`${fieldId}-source-kind`} required value={input.sourceKind ?? ''} onChange={event => set('sourceKind', event.target.value as SourceKind)}><option value="">请选择来源性质</option>{Object.entries(SOURCE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="form-field"><label htmlFor={`${fieldId}-statement-kind`}>陈述类型</label><select id={`${fieldId}-statement-kind`} required value={input.statementKind ?? ''} onChange={event => set('statementKind', event.target.value as KnowledgeInput['statementKind'])}><option value="">请选择陈述性质</option><option value="fact">事实</option><option value="constraint">约束</option><option value="recommendation">建议</option><option value="hypothesis">未核实假设（不可共享复用）</option></select></div><fieldset className="knowledge-choices"><legend>适用角色（明确选择）</legend>{Object.entries(ROLE_LABELS).map(([role, label]) => <label key={role}><input type="checkbox" checked={input.roles?.includes(role as KnowledgeRole) ?? false} onChange={event => set('roles', event.target.checked ? [...input.roles ?? [], role as KnowledgeRole] : input.roles?.filter(item => item !== role))} />{label}</label>)}</fieldset>{field('模块路径（每行一个，可留空）', 'modulePaths', { rows: 3, placeholder: 'src/example.ts' })}{field('标签（每行一个，可留空）', 'tags', { rows: 2 })}<p className="dialog-note">分类创建新的不可变候选版本，保留原正文与历史。保存候选不授予跨需求复用资格。</p></>}
    {(review.action === 'save-candidate' || review.action === 'qualify') && <details className="knowledge-body" open={review.action === 'qualify'}><summary>精确候选正文</summary><pre>{candidate?.body || '此材料正文尚未由 Host 提供；保存后须重新审阅。'}</pre></details>}
    {review.action === 'bind-remote' && <>{field('GitHub 所有者', 'owner', { required: true, maxLength: 100 })}{field('GitHub 仓库名称', 'repository', { required: true, maxLength: 100 })}{field('Pull Request 编号', 'pullRequest', { required: true, type: 'number' })}<Fact label="绑定正式目标" value={view.baseline?.formalTarget ?? '由 Host 的项目绑定决定'} /><p className="dialog-note">此绑定指向一个仓库、PR 和正式目标，之后不能静默替换。核验仅使用 GitHub 只读请求，不提交代码或执行合并。</p></>}
    {review.action === 'observe-remote' && <><Fact label="读取对象" value={`${view.remote?.owner}/${view.remote?.repository} #${view.remote?.pullRequest}`} /><Fact label="正式目标" value={view.remote?.target ?? '未绑定'} /><p className="dialog-note">记录此精确 PR 的远端状态。未知、关闭、未合入和测试响应都不会成为真实合入证据；本操作不会自动批准复用。</p></>}
    {review.action === 'qualify' && <>{field('适用的精确基线提交', 'baseline', { required: true, maxLength: 64 })}{candidate?.sourceKind === 'implementation' ? <div className="form-field"><label htmlFor={`${fieldId}-observation`}>真实合入观察</label><select id={`${fieldId}-observation`} required value={input.observationId ?? ''} onChange={event => { set('observationId', event.target.value); set('reviewed', false); }}><option value="">请选择匹配的实际观察</option>{view.observations.filter(item => item.state === 'merged' && item.provenance === 'github-live').map(item => <option key={item.observationId} value={item.observationId}>{item.observationId} · {item.formalCommit}</option>)}</select></div> : <label className="authorization-consent"><input type="checkbox" checked={input.independentOfDemand ?? false} onChange={event => set('independentOfDemand', event.target.checked)} /><span>我已核实此来源独立于本需求，不把本轮新增实现改称为既有事实或环境经验。</span></label>}{field('核验理由与依据', 'reason', { required: true, rows: 4 })}<p className="dialog-note">Host 将核验真实检查、精确基线与成果树；新增实现还必须核验已合入的正式树。这里的判断不能代替原生进程或远端证据。</p></>}
    {review.action === 'invalidate' && <>{field('撤销原因与依据', 'reason', { required: true, rows: 4 })}<p className="dialog-note">立即撤销此精确版本后续及当前读取资格，保留原文、证据和决策历史。若内容需要修正，请另建新版本并重新核验。</p></>}
    {review.action === 'propose-baseline' && <>{field('拟整合的精确提交', 'sourceCommit', { required: true, maxLength: 64 })}<Fact label="正式目标" value={view.baseline?.formalTarget ?? '尚无工作区'} /><Fact label="当前 HEAD" value={view.baseline?.head ?? '未提交'} /><p className="dialog-note">仅准备版本绑定的方案，不修改工作区。源提交必须已经存在于本地绑定的正式目标中。</p></>}
    {review.action === 'apply-baseline' && <>{proposal?.result?.state === 'conflict' && <p className="stale-warning">此操作核对并继续同一基线整合，保留原方案与源提交。请使用原操作的作者身份；不会自动 reset 或 abort 冲突。</p>}{field('本地提交作者姓名', 'authorName', { required: true, maxLength: 200 })}{field('本地提交作者邮箱', 'authorEmail', { required: true, type: 'email', maxLength: 320 })}<p className="dialog-note">明确授权将上述源提交整合到此需求工作区，可能创建本地合并提交或产生冲突。不会 push 或更改远端；整合后仍需真实能力检查，成功整合不代表功能可用。若旧内容被作废，整合完成后选择已核验的原生检查模板，Host 会在新的实际 HEAD 上重新执行。</p><label className="authorization-consent"><input type="checkbox" checked={input.reviewed ?? false} onChange={event => set('reviewed', event.target.checked)} /><span>我已核对精确提交、原 HEAD、原基线与作者身份，授权本次本地整合。</span></label></>}
    {review.action === 'verify-baseline' && <><div className="form-field"><label htmlFor={`${fieldId}-recipe-result`}>先前检查的来源成果</label><select id={`${fieldId}-recipe-result`} required value={input.resultId ?? ''} onChange={event => setInput(current => ({ ...current, resultId: event.target.value, checkIds: [] }))}><option value="">请选择含真实检查模板的先前成果</option>{[...new Set(view.checks.map(check => check.resultId))].map(resultId => <option key={resultId} value={resultId}>{resultId}</option>)}</select></div><p className="dialog-note">所选先前成果只提供已观察过的原生检查模板。Host 将在上述精确整合 HEAD 上重新运行有时间与输出上限的检查，不调用模型。旧检查通过不代表新 HEAD 已通过；只有新回执核验通过后才能登记新基线能力。</p></>}
    {(review.action === 'qualify' || review.action === 'verify-baseline') && <fieldset className="knowledge-choices"><legend>{review.action === 'verify-baseline' ? '将重新执行的原生检查模板' : '独立原生检查证据'}</legend>{checks.length ? checks.map(check => <label key={check.id}><input type="checkbox" disabled={!check.usable} checked={input.checkIds?.includes(check.id) ?? false} onChange={event => set('checkIds', event.target.checked ? [...input.checkIds ?? [], check.id] : input.checkIds?.filter(item => item !== check.id))} /><span>{check.name}<small>{check.id} · {check.environment}{!check.usable ? ' · 没有真实可用回执' : ''}</small></span></label>) : <p className="detail-muted">尚无匹配成果的原生检查。</p>}</fieldset>}
    {review.action === 'qualify' && <label className="authorization-consent"><input type="checkbox" checked={input.reviewed ?? false} onChange={event => set('reviewed', event.target.checked)} /><span>我已审阅精确正文、来源、复用价值和适用条件，确认没有混入未核实的私人结论。</span></label>}
    {unavailable && <p className="stale-warning" role="alert">{unavailable}</p>}{error && <p className="stale-warning" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button" onClick={close}>返回</button><button type="submit" className={`button ${review.action === 'invalidate' ? 'danger' : 'primary'}`} disabled={disabled}>{pending ? '正在核验…' : KNOWLEDGE_LABELS[review.action]}</button></div>
  </form>;
}
